name: Primary

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set Variables
      run: |
        echo "STACK_NAME = cf-templates" >> $GITHUB_ENV
        echo "TEMPLATE = ./infra/template.json" >> $GITHUB_ENV
        echo "REGION = us-east-1" >> $GITHUB_ENV
        echo "BUCKET_NAME = com.cuffney.cf-templates" >> $GITHUB_ENV

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Validate
      run: |
        aws cloudformation validate-template \
              --template-body file://$TEMPLATE \
              --region us-east-1

    - name: Deploy
      if: github.ref == 'refs/heads/main'
      run: |
        aws cloudformation deploy \
              --stack-name $STACK_NAME \
              --template-file $TEMPLATE \
              --no-fail-on-empty-changeset \
              --parameter-overrides \
                BucketName=$BUCKET_NAME \
              --region us-east-1
        aws s3 sync ./src s3://$BUCKET_NAME --delete